### ISSUE TITLE
Unable to activate pluging

### ISSUE THREAD

**Issue by nyetrogen** [elialgranti/geoswitch#10]
Receiving error when trying to activate plugin

Warning: require_once(/home/academy/public_html/wp-content/plugins/geoswitch/vendor/composer/autoload_static.php): failed to open stream: No such file or directory in /home/academy/public_html/wp-content/plugins/geoswitch/vendor/composer/autoload_real.php on line 28

Fatal error: require_once(): Failed opening required '/home/academy/public_html/wp-content/plugins/geoswitch/vendor/composer/autoload_static.php' (include_path='.:/usr/local/php70/pear') in /home/academy/public_html/wp-content/plugins/geoswitch/vendor/composer/autoload_real.php on line 28

**Comment by elialgranti** [comment]
Arg. Made a mistake deploying to wordpress via svn.
Try version 1.1.3 now.
