### ISSUE TITLE
How to use this plugin with wpml ? 

### ISSUE THREAD

**Issue by amaurya37** [elialgranti/geoswitch#2]
My question is .. How can we change language of wordpress page that is created  using wpml , by detecting ip address of user through GeoIP2 Precision Web Services.

**Comment by elialgranti** [comment]
I'm not familiar with WPML but according to [this post](http://wpml.org/forums/topic/setting-current-language-programmatically/) it is possible to do so programmatically.

I don't know if it is currently possible to call the plugin programmatically, and you'll need to map country to language yourself.
You might be able to get the country code by calling 'GeoSwitch::get_country_code(null, null)' from a php block within the page but I haven't tried it.

I'll add callable functions in the next release.
