### ISSUE TITLE
Can't get any response from plug-in

### ISSUE THREAD

**Issue by chris-sullivan** [elialgranti/geoswitch#3]
I've installed the plug-in and configured my Maxmind account details. I've tried it in local database mode and GeoIP2 Precision Service mode and get nothing when I add the switches to a page. It's not recognizing any locations at all. Is there some way to test if it's even interacting with the MaxMind database?

**Comment by elialgranti** [comment]
You can use the information shortcodes to see what the plugin has found.

Just copy the following code snipped into a page:
```
IP OoO [geoswitch_ip] OoO
CITY OoO [geoswitch_city] OoO
STATE OoO [geoswitch_state] OoO
STATE CODE OoO [geoswitch_state_code] OoO
COUNTRY OoO [geoswitch_country] OoO
COUNTRY CODE OoO [geoswitch_country_code] OoO
```

You should see something between the OoO markers. If not then turn debugging on in the wp_config.php file and see what error it is throwing.

Note: if you are testing locally (i.e. http://localhost/... or http://127.0.0.1/...) or using a [Private IP](http://en.wikipedia.org/wiki/Private_network) you won't get any data. You need to use a real public IP address.
