### ISSUE TITLE
What is it good for?

### ISSUE THREAD

**Issue by belz-development** [elialgranti/geoswitch#7]
It's a very interesting idea to realize such a thing. But from a SEO point of view it makes no sense.
If someone wants to be located better, then a Google Business account is much better. You can specify all your office locations there. Once this has been created, Geo tags lose their usefulness. Thus, the Local Boost on Google My Business is more than 10x higher than with Geo Tags.
After your principle with variable output depending on IP, Google can not work properly and will always return you the default value as output. The crawl Bot "Spider" is 99% from the United States and with this query there will be no effect to your local ranking chosen by IP.
If I am wrong, I ask for feedback.

With best regards

**Comment by elialgranti** [comment]
From an SEO point of view you are partially correct. In fact one of the
features I have planned for this plugin (but have not found the time to
implement) is a robots clause which would allow the web site owner to
specify what content should be shown to spider.

This plugin however is not for SEO it's for user conversion. It is the same
reason mobile apps and websites ask for your location only ip geolocation
does not require the user to agree.
One example is a restaurant chain that wants to display the information and
specials of the restaurant nearest the user as the default. The information
for all the other restaurants in the chain is available elsewhere (and
crawlable), but showing the nearest restaurant upfront may result in better
conversion (i.e. user goes to the restaurant in question).

If geolocation was not a useful feature MaxMind (the company that makes the
databases my plugin uses) would not exist.

The reason I wrote this plugin is that all the other ones available (at the
time) used the old MaxMind libraries and no-one had bothered to update them
to the new format so the available databases for those plugins had not been
updated in quite a while.

Regards,
Eli
