### ISSUE TITLE
Comma separated state codes or names in one geoswitch_case not functioning.

### ISSUE THREAD

**Issue by scottbclark** [elialgranti/geoswitch#8]
Hi, 
Trying to display a set of phone numbers in my footer based on state code. This code works to display just the first phone number in RI:

```
[geoswitch]
[geoswitch_case state_code="RI"]Tel. (401) 273-5530[/geoswitch_case]
[geoswitch_case]Tel. (401) 273-5530<br/>Tel. (717) 562-0669[/geoswitch_case]
[/geoswitch]
```

But the following displays both numbers to RI based IP addresses

```
[geoswitch]
[geoswitch_case state_code="RI, MA, CT"]Tel. (401) 273-5530[/geoswitch_case]
[geoswitch_case]Tel. (401) 273-5530<br/>Tel. (717) 562-0669[/geoswitch_case]
[/geoswitch]
```

I've tried it without spaces and with a comma last as well. 
Thanks!

**Comment by elialgranti** [comment]
I'll take a look. There may be a bug. Meantime if single codes work a
workaround can be:

[geoswitch]
[geoswitch_case state_code="RI"]Tel (401) 273-5530[/geoswitch_case]
geoswitch_case state_code="MA"]Tel (401) 273-5530[/geoswitch_case]
geoswitch_case state_code="CT"]Tel (401) 273-5530[/geoswitch_case]
[geoswitch_case]Tel (401) 273-5530<br/>Tel (717) 562-0669[/geoswitch_case]
[/geoswitch]

Eli

**Comment by scottbclark** [comment]
Great thanks. Excellent plugin btw.

On Friday, February 5, 2016, Eli Algranti <notifications@github.com> wrote:

> I'll take a look. There may be a bug. Meantime if single codes work a
> workaround can be:
>
> [geoswitch]
> [geoswitch_case state_code="RI"]Tel (401) 273-5530[/geoswitch_case]
> geoswitch_case state_code="MA"]Tel (401) 273-5530[/geoswitch_case]
> geoswitch_case state_code="CT"]Tel (401) 273-5530[/geoswitch_case]
> [geoswitch_case]Tel (401) 273-5530<br/>Tel (717) 562-0669[/geoswitch_case]
> [/geoswitch]
>
> Eli
> On 6 Feb 2016 5:01 am, "scottbclark" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Hi,
> > Trying to display a set of phone numbers in my footer based on state code
> > This code works to display just the first phone number in RI:
> >
> > [geoswitch]
> > [geoswitch_case state_code="RI"]Tel (401) 273-5530[/geoswitch_case]
> > [geoswitch_case]Tel (401) 273-5530<br/>Tel (717)
> 562-0669[/geoswitch_case]
> > [/geoswitch]
> >
> > But the following displays both numbers to RI based IP addresses
> >
> > [geoswitch]
> > [geoswitch_case state_code="RI, MA, CT"]Tel (401)
> 273-5530[/geoswitch_case]
> > [geoswitch_case]Tel (401) 273-5530<br/>Tel (717)
> 562-0669[/geoswitch_case]
> > [/geoswitch]
> >
> > I've tried it without spaces and with a comma last as well
> > Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/elialgranti/geoswitch/issues/8>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elialgranti/geoswitch/issues/8#issuecomment-180606031>
> .
>


-- 



Scott Clark
Creative Director


*COMMUNITY BANKMARKETING SOLUTIONS*

scott@teamcbms.com
401-273-5530 x213
401-236-1298 *direct*

-- 


This e-mail and any attachments are provided for the sole use of the 
intended recipient(s), and may contain information that is confidential, 
privileged, proprietary or otherwise protected by law. If you are not the 
intended recipient of this message, you are not authorized to read, print, 
retain, copy, forward or otherwise disseminate this message or any part of 
it. If you have received this e-mail in error, please notify the sender 
immediately by reply e-mail and destroy all copies of the original 
communication

**Comment by elialgranti** [comment]
Hi Scott,
Finally got around to recreating my development environment for this plugin. It seems the comma separated value support was never implemented. Either I forgot to do it or it was left un-pushed in my old computer. In any case it should work in the new version of the plugin if still relevant.
