### ISSUE TITLE
GeoSwitch seams not to work on WP 2017

### ISSUE THREAD

**Issue by mikebrazil** [elialgranti/geoswitch#9]
I've just updated my website to the current WP version with twenty seventeen theme and the shortcodes are just ignored in the front end. It was working (and still is) with previous theme (not wp default theme but another theme I intalled previously). Please advise.

**Comment by elialgranti** [comment]
Sorry, I have not been updating this plugin. I'll try and take a look but
cannot make promises as to the time frame. If you can fork from github and
send me a patch I'll be sure to incorporate it.

**Comment by mikebrazil** [comment]
I noticed that the fallback case worked (no country_code rulers), so the plugin works at most. Problem seams to be in listing multiple country codes by comma separate values. I found a workaround here in a previous issue topic (about state_code) and applied same work logic listing one by one and it did work. In case you consider to improve it someday we'd be glad to know, it's a very handy add-on. We wonder if it would work directly on the php file, perhaps with do_shortcode function? We've tried but it didn't work, as follows:
<?php echo do_shortcode("[geoswitch]"); ?>
<?php echo do_shortcode("[geoswitch_case country_code='SE']"); ?>Go Sweden!<?php echo do_shortcode("[/geoswitch_case]"); ?>
<?php echo do_shortcode("[geoswitch_case country_code='PT']"); ?>Go Portugal!<?php echo do_shortcode("[/geoswitch_case]"); ?>
<?php echo do_shortcode("[geoswitch_case]"); ?>Go USA!<?php echo do_shortcode("[/geoswitch_case]"); ?>
<?php echo do_shortcode("[/geoswitch]"); ?>

**Comment by elialgranti** [comment]
Can you send me the shortcut that is not working?

**Comment by mikebrazil** [comment]
It did work directly on the php file as follows:
<title>
<?php echo do_shortcode("
[geoswitch]
[geoswitch_case country_code='SE']Swedish title[/geoswitch_case]
[geoswitch_case country_code='FR']French title[/geoswitch_case]
[geoswitch_case country_code='BE']French title[/geoswitch_case]
(...)
[geoswitch_case]English title[/geoswitch_case]
[/geoswitch]"); ?>
</title>
but it doesn't work as
<title>
<?php echo do_shortcode("
[geoswitch]
[geoswitch_case country_code='SE']Swedish title[/geoswitch_case]
[geoswitch_case country_code='FR,BE']French title[/geoswitch_case]<------- gets ignored in case either FR or BE are detected by geolocation, and fallback case (english) gets set.
(...)
[geoswitch_case]English title[/geoswitch_case]
[/geoswitch]"); ?>
</title>

**Comment by elialgranti** [comment]
Hi Mike,
I've updated the plugin. Comma separated values should now work.
Note, I think you figured it out but, when using do_shortcode() the parameter must include the whole shortcode. This means all the text between opening and closing tags for block shortcodes.
